project:
  type: website

website:
  title: "Polyclimate"
  site-url: "https://polyclimate.org"
  search: false
  navbar:
    right:
      - about.qmd
      #- icon: github
      #  href: https://github.com/
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    html-math-method: katex
resources:
  - CNAME


